/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SponsorRouteImport } from './routes/sponsor'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as SamplesIdRouteImport } from './routes/samples.$id'
import { Route as CategoryCatRouteImport } from './routes/category.$cat'
import { Route as AuthenticatedThanksRouteImport } from './routes/_authenticated/thanks'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated/store'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedOrdersNewRouteImport } from './routes/_authenticated/orders.new'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders.$id'
import { Route as AuthenticatedMessagesUserIdRouteImport } from './routes/_authenticated/messages.$userId'
import { Route as AuthenticatedPayKindIdRouteImport } from './routes/_authenticated/pay.$kind.$id'

const SponsorRoute = SponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesIdRoute = SamplesIdRouteImport.update({
  id: '/samples/$id',
  path: '/samples/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCatRoute = CategoryCatRouteImport.update({
  id: '/category/$cat',
  path: '/category/$cat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedThanksRoute = AuthenticatedThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersNewRoute = AuthenticatedOrdersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedOrdersRoute,
} as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedOrdersRoute,
} as any)
const AuthenticatedMessagesUserIdRoute =
  AuthenticatedMessagesUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedMessagesRoute,
  } as any)
const AuthenticatedPayKindIdRoute = AuthenticatedPayKindIdRouteImport.update({
  id: '/pay/$kind/$id',
  path: '/pay/$kind/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/sponsor': typeof SponsorRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/store': typeof AuthenticatedStoreRoute
  '/thanks': typeof AuthenticatedThanksRoute
  '/category/$cat': typeof CategoryCatRoute
  '/samples/$id': typeof SamplesIdRoute
  '/u/$username': typeof UUsernameRoute
  '/messages/$userId': typeof AuthenticatedMessagesUserIdRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/orders/new': typeof AuthenticatedOrdersNewRoute
  '/pay/$kind/$id': typeof AuthenticatedPayKindIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/sponsor': typeof SponsorRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/store': typeof AuthenticatedStoreRoute
  '/thanks': typeof AuthenticatedThanksRoute
  '/category/$cat': typeof CategoryCatRoute
  '/samples/$id': typeof SamplesIdRoute
  '/u/$username': typeof UUsernameRoute
  '/messages/$userId': typeof AuthenticatedMessagesUserIdRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/orders/new': typeof AuthenticatedOrdersNewRoute
  '/pay/$kind/$id': typeof AuthenticatedPayKindIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/sponsor': typeof SponsorRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/store': typeof AuthenticatedStoreRoute
  '/_authenticated/thanks': typeof AuthenticatedThanksRoute
  '/category/$cat': typeof CategoryCatRoute
  '/samples/$id': typeof SamplesIdRoute
  '/u/$username': typeof UUsernameRoute
  '/_authenticated/messages/$userId': typeof AuthenticatedMessagesUserIdRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/_authenticated/orders/new': typeof AuthenticatedOrdersNewRoute
  '/_authenticated/pay/$kind/$id': typeof AuthenticatedPayKindIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/auth'
    | '/browse'
    | '/sponsor'
    | '/admin'
    | '/dashboard'
    | '/messages'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/store'
    | '/thanks'
    | '/category/$cat'
    | '/samples/$id'
    | '/u/$username'
    | '/messages/$userId'
    | '/orders/$id'
    | '/orders/new'
    | '/pay/$kind/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/auth'
    | '/browse'
    | '/sponsor'
    | '/admin'
    | '/dashboard'
    | '/messages'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/store'
    | '/thanks'
    | '/category/$cat'
    | '/samples/$id'
    | '/u/$username'
    | '/messages/$userId'
    | '/orders/$id'
    | '/orders/new'
    | '/pay/$kind/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/apply'
    | '/auth'
    | '/browse'
    | '/sponsor'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/orders'
    | '/_authenticated/profile'
    | '/_authenticated/store'
    | '/_authenticated/thanks'
    | '/category/$cat'
    | '/samples/$id'
    | '/u/$username'
    | '/_authenticated/messages/$userId'
    | '/_authenticated/orders/$id'
    | '/_authenticated/orders/new'
    | '/_authenticated/pay/$kind/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  SponsorRoute: typeof SponsorRoute
  CategoryCatRoute: typeof CategoryCatRoute
  SamplesIdRoute: typeof SamplesIdRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sponsor': {
      id: '/sponsor'
      path: '/sponsor'
      fullPath: '/sponsor'
      preLoaderRoute: typeof SponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples/$id': {
      id: '/samples/$id'
      path: '/samples/$id'
      fullPath: '/samples/$id'
      preLoaderRoute: typeof SamplesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$cat': {
      id: '/category/$cat'
      path: '/category/$cat'
      fullPath: '/category/$cat'
      preLoaderRoute: typeof CategoryCatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/thanks': {
      id: '/_authenticated/thanks'
      path: '/thanks'
      fullPath: '/thanks'
      preLoaderRoute: typeof AuthenticatedThanksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/new': {
      id: '/_authenticated/orders/new'
      path: '/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AuthenticatedOrdersNewRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
    '/_authenticated/messages/$userId': {
      id: '/_authenticated/messages/$userId'
      path: '/$userId'
      fullPath: '/messages/$userId'
      preLoaderRoute: typeof AuthenticatedMessagesUserIdRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/_authenticated/pay/$kind/$id': {
      id: '/_authenticated/pay/$kind/$id'
      path: '/pay/$kind/$id'
      fullPath: '/pay/$kind/$id'
      preLoaderRoute: typeof AuthenticatedPayKindIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedMessagesRouteChildren {
  AuthenticatedMessagesUserIdRoute: typeof AuthenticatedMessagesUserIdRoute
}

const AuthenticatedMessagesRouteChildren: AuthenticatedMessagesRouteChildren = {
  AuthenticatedMessagesUserIdRoute: AuthenticatedMessagesUserIdRoute,
}

const AuthenticatedMessagesRouteWithChildren =
  AuthenticatedMessagesRoute._addFileChildren(
    AuthenticatedMessagesRouteChildren,
  )

interface AuthenticatedOrdersRouteChildren {
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
  AuthenticatedOrdersNewRoute: typeof AuthenticatedOrdersNewRoute
}

const AuthenticatedOrdersRouteChildren: AuthenticatedOrdersRouteChildren = {
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
  AuthenticatedOrdersNewRoute: AuthenticatedOrdersNewRoute,
}

const AuthenticatedOrdersRouteWithChildren =
  AuthenticatedOrdersRoute._addFileChildren(AuthenticatedOrdersRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRoute
  AuthenticatedThanksRoute: typeof AuthenticatedThanksRoute
  AuthenticatedPayKindIdRoute: typeof AuthenticatedPayKindIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStoreRoute: AuthenticatedStoreRoute,
  AuthenticatedThanksRoute: AuthenticatedThanksRoute,
  AuthenticatedPayKindIdRoute: AuthenticatedPayKindIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApplyRoute: ApplyRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  SponsorRoute: SponsorRoute,
  CategoryCatRoute: CategoryCatRoute,
  SamplesIdRoute: SamplesIdRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
